### ISSUE TITLE
need way to globally modify metrics

### ISSUE THREAD

**Issue by mythmon** [willkg/markus#40]
We've started to use Markus [on Normandy](https://github.com/mozilla/normandy/pull/1856). Thanks for making it easy to integrate!

I think a good addition to Markus would be a middleware system, that could process the data before it is sent to the backend. This would help us solve a problem we're having on Normandy.

One [the requests](https://github.com/mozilla/normandy/pull/1856#issuecomment-483716416) we had from Ops was the ability to have global tags that could be controlled via environment variables. Specifically, we wanted to add a tag to canary instances so we could compare their stats against the general population.

Instead of updating every single metrics call location with this functionality, I thought to add it as a part of the config. The only configurable place I could find to do this was the backends. Making custom backends to do this either ended up being very repetitive, or complicated and hard to test. It also means that any backend we added would have to have the same modifications, which is hard to enforce.

What do you think? I could work on a PR to add this feature if you think it's a good feature for Markus to have.

**Comment by willkg** [comment]
Doing it in the backend is interesting. You could create a backend wrapper that injects the tags. I can sketch that out more if that's interesting and/or doesn't make any sense.

**Comment by willkg** [comment]
We could adjust all the backends, too. Some of the backends have a prefix option. Seems like we could have default tags work like that.

**Comment by mythmon** [comment]
I think a backend wrapper would probably be easier, but I couldn't get it to work in a way I was happy with. I'd be happy to see what you come up with.

Global tags as a default option would also work. I can't think off hand of any other use cases for a middleware.

**Comment by willkg** [comment]
I think the implementation of these options isn't hard, so let's talk ergonomics.

If we added prefixes and default tags to all the backends, then we'd configure it when configuring the backends. How does something like this feel?:

```python
markus.configure(
    backends=[
        {
            # Log metrics to the logs
            'class': 'markus.backends.logging.LoggingMetrics',
            'prefix': 'myproject',
            'tags': ['key:val', 'key2:val2'],
        },
        {
            # Log metrics to Datadog
            'class': 'markus.backends.datadog.DatadogMetrics',
            'prefix': 'myproject',
            'tags': ['key:val', 'key2:val2'],
            'options': {
                'statsd_host': 'example.com',
                'statsd_port': 8125,
                'statsd_namespace': ''
            }
        }
    ]
)
```

The Python logging module has a filter system for injecting data into messages as they go through. Maybe something like that is helpful here, too. You could use it to add prefixes, add tags, adjust numbers, filter things out, etc, and do it depending on the metric data.

So that might look like this:

```python
def add_data(datatype, stat, value, tags):
    stat = 'myproject.' + stat
    tags.append('key:val')

markus.configure(
    backends=[
        {
            # Log metrics to the logs
            'class': 'markus.backends.logging.LoggingMetrics',
            'filters': [add_data],
        },
        {
            # Log metrics to Datadog
            'class': 'markus.backends.datadog.DatadogMetrics',
            'filters': [add_data],
            'options': {
                'statsd_host': 'example.com',
                'statsd_port': 8125,
                'statsd_namespace': ''
            }
        }
    ]
)
```

Maybe we can add filters to the `MetricsInterface`, too, so then you could use them for metrics for a specific client or global to your project. I think that should be pretty straight-forward to implement.

How do you feel about these options?

**Comment by mythmon** [comment]
> Maybe we can add filters to the MetricsInterface, too, so then you could use them for metrics for a specific client or global to your project.

Is there a way to configure the MetricsInterface globally in a project? Or do you mean creating an interface once and sharing it around the project?

Adding this to the backends, either as a filter or as a builtin option looks pretty clean, but I don't really know how I would test it. The Markus testing tools seem to completely ignore the backends. That means it would be difficult to write a unit test that the extra tags actually get added.

That's the main reason I was hoping to have this behavior separate from the backends: I'd expect that the testing infrastructure would take into account default tags and prefixes and any other filter behaviors.

I also can't think of a case where I'd want different tags on a per-backend basis. Maybe that's a lack of creativity and experience though.

**Comment by willkg** [comment]
>> Maybe we can add filters to the MetricsInterface, too, so then you could use them for metrics for a specific client or global to your project.
> 
> Is there a way to configure the MetricsInterface globally in a project? Or do you mean creating an interface once and sharing it around the project?

The MetricsInterface is just like a logger--you could have one global to the project or one per Python module or a mish mash of all possible options. Any of those are fine.

I was thinking that if we implemented filters on the MetricsInterface, it gives developers a lot of flexibility on filters and defaults and values and such in their project. Technically, the MetricsInterface adds a prefix to all the metrics that get generated with it. Seems like adding filters to that is nice, too, maybe.

The testing situation is interesting. Definitely want to be able to test filters. I'll have to think about how that might work. You're right in that testing completely ignores differences in backends currently. That was intentional, but maybe a bad idea?

**Comment by mythmon** [comment]
I think the current testing setup is quite nice, because it works at the level of abstraction I'm interested in. The code that I'm testing doesn't care about the backends, so the tests for that code don't need to either.

On the other hand, the current set up doesn't do much to help test custom backends. I think that's ok though, since custom backends will require pretty custom testing code too. The tests for the data dog backend tests seem like a good example of that.

**Comment by willkg** [comment]
I landed the "emit records" overhaul. Now that that's done, we need to add filtering. I'll work on that soon.
